### ISSUE TITLE
updates to track tooltips

### ISSUE THREAD

**Issue by tmazor** [hms-dbmi/OncoThreads#141]
I think the text to promote the variable gets lost in the current tooltip. Let's make it into 3 lines of text instead:
Variable Name
Description
Click to promote this variable

So for this:
![image](https://user-images.githubusercontent.com/10508276/51213502-25139e00-18e9-11e9-8468-865a4f446db1.png)

The new version would be:
Cancer Type
Description: Cancer Type
Click to promote this variable

**Comment by ThHarbig** [comment]
What do you think about getting rid of the description in the tooltip? They can be quite long and they are already displayed when adding variables. 

Also it could be quite useful to make it clearer that the action can be applied to multiple timepoints using the context menu that appears with a right-click.

Something like:
Click to promote variable "CancerType"
(Right click for more options)
