### ISSUE TITLE
variable explorer selection behavior

### ISSUE THREAD

**Issue by tmazor** [hms-dbmi/OncoThreads#225]
In the variable explorer, I can click on the check box to select multiple variables to add. However, clicking anywhere else in the row (e.g. variable name) selects that variable while de-selecting all other variables. Can you make it so that clicking anywhere in the row selects that variable without de-selecting other variables?
![Nov-08-2019 18-05-03](https://user-images.githubusercontent.com/10508276/68516557-51225600-0252-11ea-984e-27f4ec0a04f1.gif)

**Comment by ThHarbig** [comment]
I can look into it, but I suspect that this might be a LineUp functionality that could be hard for us to change
