### ISSUE TITLE
file upload - required files

### ISSUE THREAD

**Issue by tmazor** [hms-dbmi/OncoThreads#239]
Right now, one of clinical sample or clinical patient or mutations file are required. What if the only data I have is copy number data? Or some other molecular profile. Isn't that the same as only having mutations? Shouldn't we require one of clinical sample or clinical patient or any molecular profile?

Perhaps this is why? We normally show a single clinical track as the initial OncoThreads view. If I only provide mutations, then we can show mutation count. But if I only provide any of the other molecular tracks, then we have nothing to show.

If that's the reason, then we could require one clinical file and then all molecular profiles, including mutations,  become optional.

**Comment by ThHarbig** [comment]
I'm not sure if I understand your last sentence. You're right we need clinical data or mutation data (for mutation counts) to display something. Do you want to move mutation data from "at least one required" to "optional"?

Another possibility (which might be somewhat hard to implement) is that we do not require clinical data or mutations. We just require any data that can be mapped to samples. We could just display the samples as "empty" if we do not have predefined variables. 

For example, we could just display all samples as gray rectangles if there is no predefined data. As soon as the user adds a genetic variable we can replace the gray rectangles with data.
