### ISSUE TITLE
improve the state summary panel

### ISSUE THREAD

**Issue by wangqianwen0418** [hms-dbmi/OncoThreads#255]
currently, it is hard to read and compare from the pure-text-based summary.

**Comment by wangqianwen0418** [comment]
<img width="420" alt="image" src="https://user-images.githubusercontent.com/19774198/103560688-2ba8d080-4e86-11eb-9692-4fb59b5df5c3.png">

1. it is almost impossible to read value from the gradient  
2. pure text description is hard to compare  
3. when one state has relatively small number of patients, its width is small and it is hard to read. Can we choose another visual channel to encode the number of patients?  
4. can we merge these two panel? They serve the same purpose

**Comment by wangqianwen0418** [comment]
![Untitled_Artwork 17](https://user-images.githubusercontent.com/19774198/103903152-867e3a00-50c9-11eb-8757-7fe104a987c0.png)

In all the three design options, I want to resolve the ambiguity of color encoding.

- option 1; For each attribute, we show the attribute distribution of each state. X-axis indicates the value of attributes (works for both categorical and numerical), and y-axis indicates the number of patients.

- option 2 simply modify the layout of option 1. So that the layout is consistent with the one used in the sankey diagram (i.e., state in the horizontal direction and attribute in the vertical direction). But the problem is, the reordering makes it hard to compare the distribution of different states.

- option 3 is relatively harder to understand than option 1&2. Each patient is represented by a bar whose height indicates the value of the corresponding attribute. 
The advantage of this design is that a) the encoding can be adopted to the sankey diagram; 2) the width of the chart indicates the number of patients

**Comment by wangqianwen0418** [comment]
I have implemented O2 and O3;

- O2: 
![image](https://user-images.githubusercontent.com/19774198/104213860-c3696a00-5404-11eb-81e5-f7d3c27959f8.png)

-O3:
![image](https://user-images.githubusercontent.com/19774198/104220677-d6cd0300-540d-11eb-8625-21427891aa45.png)

**Comment by ngehlenborg** [comment]
Great!

I think it would be very helpful if you could move the labels for the variables somehow so that we can see them without tool tips/hovering.

**Comment by wangqianwen0418** [comment]
when the height of a chart is too small, add a scaled chart in the tooltip
<img src="https://user-images.githubusercontent.com/19774198/104636844-f8c6bf80-5671-11eb-8384-d3aeb96be481.png" width="400"/>

**Comment by wangqianwen0418** [comment]
<img src="https://user-images.githubusercontent.com/19774198/106008751-9dd79400-6085-11eb-8686-8e11702e7c24.png" width="600"/>
